# Generated by Django 4.2.11 on 2024-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rated', models.CharField(max_length=500)),
                ('released', models.CharField(max_length=500)),
                ('runtime', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=500)),
                ('plot', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('awards', models.CharField(max_length=500)),
                ('actors', models.ManyToManyField(related_name='movies', to='movie_app.actor')),
                ('director', models.ManyToManyField(related_name='movies', to='movie_app.director')),
            ],
        ),
    ]
